# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b09bb72a2675c700e849d50ac3a9cbe0"
name = "stockpilot"
application_url = "https://reply-ing-million-mesh.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "inventory_levels/update" ]
  uri = "/webhooks/inventory/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,write_products,read_products,write_inventory"
 
[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "https://example.com/apps/stockpilot"
subpath = "api"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true